### ISSUE TITLE
How to handle MFA code for deployment of services

### ISSUE THREAD

**Issue by s1mrankaur** [fourTheorem/slic-starter#131]
In deploy-module.sh https://github.com/fourTheorem/slic-starter/blob/master/build-scripts/deploy-module.sh, we have 

../node_modules/serverless/bin/serverless deploy --stage ${SLIC_STAGE} --region ${TARGET_REGION} --package build-artifacts/${SLIC_STAGE} --force

We have MFA enabled on the account and need to pass it for deployment. How can that be handled here?

**Comment by eoinsha** [comment]
There is nothing specific to AWS credentials in SLIC Starter.

How are AWS credentials set in your environment? Are you using `AWS_` environment variables or a named profile?

**Comment by s1mrankaur** [comment]
@eoinsha We are using named profiles.

**Comment by s1mrankaur** [comment]
Needed the CI/CD pipeline to use the a pre-configured deployment-role instead of profiles.
