### ISSUE TITLE
How do we add a co-relationId to our the logger to trace the request properly 

### ISSUE THREAD

**Issue by s1mrankaur** [fourTheorem/slic-starter#141]
How can we add the **co-relationId** for the Pino logger to trace the request as it flows through the system?

**Comment by lmammino** [comment]
Hello @s1mrankaur 👋🏽 

If I understand your question correctly, you are looking for a way to propagate tracing information while logging using `pino`.

This is something that I haven't tried myself yet, but I could find an interesting example online (source: https://tlvince.com/decorated-lambda-handlers):

```javascript
const https = require('https')
const got = require('got')
const pino = require('pino')
const AWSXRay = require('aws-xray-sdk-core')

const parentLogger = pino({
  base: {
    memorySize: process.env.AWS_LAMBDA_FUNCTION_MEMORY_SIZE,
    region: process.env.AWS_REGION,
    runtime: process.env.AWS_EXECUTION_ENV,
    version: process.env.AWS_LAMBDA_FUNCTION_VERSION,
  },
  name: process.env.AWS_LAMBDA_FUNCTION_NAME,
  level: process.env.LOG_LEVEL || 'info',
  useLevelLabels: true,
})

exports.handler = (event, context) => {
  AWSXRay.captureHTTPsGlobal(https)

  const logger = parentLogger.child({
    traceId: process.env._X_AMZN_TRACE_ID,
    awsRequestId: context.awsRequestId,
  })

  logger.info({ uuid: 'foo' }, 'hello world')
}
```

Let us know if this is helpful 🙂

**Comment by s1mrankaur** [comment]
Perfect! Thanks for sharing :) I ended up using https://www.npmjs.com/package/pino-lambda . Thanks for your prompt response though. It helped.
