### ISSUE TITLE
Add pipeline view SAR application

### ISSUE THREAD

**Issue by eoinsha** [fourTheorem/slic-starter#61]
Suggestion by @heitorlessa - add a dashboard for SLIC Starter CD by including the Pipeline Dashboard into the deployment.

See:
- https://github.com/stelligent/pipeline-dashboard
- https://stelligent.com/2017/11/16/codepipeline-dashboard/

**Comment by eoinsha** [comment]
The Pipeline Dashboard is only deployed to two US regions in the SAR. We deploy sliclists.com to `eu-west-1` so this is not going to be an easy solution without moving regions. Closing for now. The dashboard can be deployed from the https://github.com/stelligent/pipeline-dashboard repo for anyone who needs it.

**Comment by heitorlessa** [comment]
Hey Eoin - I can check, but are you sure it only deploys in us-east? I have
run workshops in Ireland region with that solution though.

SAR Apps, when deployed to us-east-1 and made public, the artefact is
replicated to all regions.

**Comment by eoinsha** [comment]
Hi Heitor, Let me check again and see what I might have been doing wrong. It'd be great to get this working.

**Comment by heitorlessa** [comment]
Ping me today when you’re trying or else I can do this on Monday morning

**Comment by eoinsha** [comment]
Fixed with PR #70, thanks @heitorlessa
