### ISSUE TITLE
CORS Developer Resources - Include some docs?

### ISSUE THREAD

**Issue by harveymatt** [fourTheorem/slic-starter#65]
https://github.com/fourTheorem/slic-starter/blob/28c0d98e4a13c69061c5addfe523b56b0cb9df7f/user-service/lib/response.js#L6

https://github.com/fourTheorem/slic-starter/blob/28c0d98e4a13c69061c5addfe523b56b0cb9df7f/user-service/sls-functions.yml#L9

Maybe worth including a security subheading in the readme including some references to CORS?

Developer References:
1 https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
2 https://serverless.com/framework/docs/providers/aws/events/apigateway#enabling-cors

**Comment by eoinsha** [comment]
Good suggestion, happy to add this. PRs also welcome.
