### ISSUE TITLE
Add password reset / force password change

### ISSUE THREAD

**Issue by eoinsha** [fourTheorem/slic-starter#77]
Integrate Cognito support

**Comment by paulkevany** [comment]
Happy to integrate this - probably requires the following?

- https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#forgotPassword-property

- https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#changePassword-property
